-- Run this in your Supabase SQL Editor to fix the schema cache error for the expenses table

-- Create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    category TEXT,
    detail TEXT,
    amount NUMERIC,
    vehicle TEXT,
    module TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add any missing columns to 'expenses' table if the table already existed
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS detail TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vehicle TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS module TEXT;

-- Reload the PostgREST schema cache
NOTIFY pgrst, 'reload schema';
