import { createClient } from '@/utils/supabase/server'
import { cookies } from 'next/headers'
import { AlertCircle } from 'lucide-react'
import Link from 'next/link'
import AddTodoForm from './add-form'
import TodoItem from './todo-item'

export default async function Page() {
  const cookieStore = await cookies()
  const supabase = createClient(cookieStore)

  const { data: todos, error } = await supabase.from('todos').select().order('inserted_at', { ascending: false })

  if (error && error.code === '42P01') {
    return (
      <div className="min-h-screen bg-mesh flex items-center justify-center p-6">
        <div className="glass p-12 rounded-4xl max-w-lg text-center animate-fade-in">
          <div className="w-20 h-20 bg-danger/10 rounded-3xl flex items-center justify-center mb-8 mx-auto">
            <AlertCircle className="w-10 h-10 text-danger" />
          </div>
          <h1 className="text-3xl font-black text-text-primary mb-4 uppercase">Table Missing</h1>
          <p className="text-text-secondary font-medium mb-8">
            The <code className="bg-slate-100 px-2 py-1 rounded">todos</code> table hasn't been created in your Supabase project yet.
          </p>
          <div className="bg-slate-900 text-slate-100 p-6 rounded-2xl text-left font-mono text-sm mb-8 overflow-x-auto shadow-inner">
            <pre>{`CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);`}</pre>
          </div>
          <p className="text-text-muted text-xs font-bold uppercase tracking-widest">
            Run the SQL above in your Supabase SQL Editor
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-mesh p-4 sm:p-8 md:p-12">
      <div className="max-w-2xl mx-auto">
        <div className="mb-12">
          <h1 className="text-2xl sm:text-4xl md:text-5xl font-black tracking-tighter text-text-primary uppercase">
            My <span className="text-gradient">Tasks</span>
          </h1>
          <p className="text-text-secondary font-bold tracking-[0.2em] uppercase text-[10px] mt-1">
            Supabase Connection Test
          </p>
        </div>

        <AddTodoForm />

        <div className="grid gap-4">
          {todos && todos.length > 0 ? (
            todos.map((todo) => (
              <TodoItem key={todo.id} todo={todo} />
            ))
          ) : (
            <div className="glass p-20 rounded-4xl text-center border-dashed border-2 border-primary/20">
              <p className="text-text-muted font-bold uppercase tracking-widest text-sm">No tasks found</p>
              <p className="text-text-secondary text-xs mt-2">Start by adding a new task above</p>
            </div>
          )}
        </div>

        <div className="mt-12 text-center">
          <Link href="/" className="text-text-muted font-bold text-[10px] uppercase tracking-widest hover:text-primary transition-colors">
            ← Back to Gateway
          </Link>
        </div>
      </div>
    </div>
  )
}


